### ISSUE TITLE
Match features with the deprecated <marquee> element

### ISSUE THREAD

**Issue by adueppen** [TheAndroidMaster/Scrurl#1]
In order for this to be useful, it needs to implement all the features of the <marquee> element in HTML, as found [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/marquee).

**Comment by fennifith** [comment]
Well that's definitely a misleading title.

**Comment by adueppen** [comment]
@TheAndroidMaster I put a whole 15 seconds of thought into this joke how dare you criticize me

**Comment by fennifith** [comment]
The only features of the element that can really be implemented are the direction and scrollamount attributes, both of which can be added pretty easily. I think I'll rename the 'speed' parameter to 'scrolldelay' while I'm at it, for consistency.
